import type { TemplateManifest } from "@shandapha/contracts";

export const templateGroups = {
  shells: ["AdminShell", "MarketingShell", "DocsShell", "SidebarShell"],
  blocks: [
    "auth/login-01",
    "auth/signup-01",
    "dashboard-01",
    "dashboard-sidebar",
    "docs-article",
    "pricing-grid",
    "faq-accordion",
    "legal-shell",
    "contact-shell",
    "marketing-hero",
  ],
  saas: [
    "dashboard-home",
    "list-filters",
    "detail-tabs-timeline",
    "form-create-edit",
    "settings-sectioned",
    "team-roles-starter",
    "billing-plans-starter",
    "onboarding-3-step",
    "auth/sign-in",
    "auth/sign-up",
    "auth/forgot",
    "auth/reset",
  ],
  marketing: [
    "landing-section-based",
    "pricing-basic",
    "faq",
    "contact",
    "legal-layout",
  ],
  docs: [
    "docs-home",
    "docs-article",
    "blog-index",
    "blog-article",
    "changelog",
  ],
} as const;

export const templates: TemplateManifest[] = [
  {
    slug: "dashboard-home",
    name: "Dashboard Home",
    group: "saas",
    shell: "AdminShell",
    summary: "Overview shell with KPI rails, chart cards, activity cards, and action slots.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["executive", "ops", "support"],
    blocks: ["dashboard-01", "dashboard-sidebar", "chart-area", "datatable-basic"],
    related: ["list-filters", "billing-plans-starter", "team-roles-starter"],
    surfaces: ["chart container", "data table baseline", "sidebar shell", "section cards"],
    featuredPackIds: ["normal", "glass", "neon"],
    dataContract: {
      entities: ["workspace", "usageMetric", "member", "auditEntry"],
      slots: ["heroActions", "kpiRail", "chartRegion", "tableRegion"],
      outputs: ["dashboard overview", "trend summary", "team activity"],
      samples: ["workspace-summary.json", "usage-timeseries.json"],
    },
  },
  {
    slug: "list-filters",
    name: "List Filters",
    group: "saas",
    shell: "AdminShell",
    summary: "Dense index page with filters, saved views, bulk actions, and table affordances.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["simple", "advanced"],
    blocks: ["datatable-basic", "toolbar-filters", "bulk-actions"],
    related: ["dashboard-home", "detail-tabs-timeline"],
    surfaces: ["data toolbar", "table baseline", "bulk action bar"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["record", "savedView", "filterOption"],
      slots: ["toolbar", "table", "secondaryPanel"],
      outputs: ["filtered list", "saved view metadata"],
      samples: ["records.json", "filters.json"],
    },
  },
  {
    slug: "detail-tabs-timeline",
    name: "Detail Tabs Timeline",
    group: "saas",
    shell: "SidebarShell",
    summary: "Entity detail screen with summary card, tabs, timeline, and related activity.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["client-service", "b2b account"],
    blocks: ["detail-overview", "activity-timeline", "related-items"],
    related: ["list-filters", "settings-sectioned"],
    surfaces: ["tabs", "items", "timeline rail"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["account", "event", "relatedEntity"],
      slots: ["summary", "tabPanels", "timeline", "relatedStrip"],
      outputs: ["record summary", "recent events", "linked entities"],
      samples: ["account.json", "events.json"],
    },
  },
  {
    slug: "form-create-edit",
    name: "Form Create Edit",
    group: "saas",
    shell: "AdminShell",
    summary: "Structured create/edit flows with helper copy, sections, and action rails.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["single column", "sectioned"],
    blocks: ["form-sections", "field-group", "success-panel"],
    related: ["settings-sectioned", "auth/sign-up"],
    surfaces: ["field", "input group", "validation", "success state"],
    featuredPackIds: ["normal", "glass", "neon"],
    dataContract: {
      entities: ["draft", "policy", "validationIssue"],
      slots: ["hero", "formSections", "aside"],
      outputs: ["draft payload", "validation state", "review summary"],
      samples: ["form-draft.json", "form-schema.json"],
    },
  },
  {
    slug: "settings-sectioned",
    name: "Settings Sectioned",
    group: "saas",
    shell: "SidebarShell",
    summary: "Settings shell with grouped controls, policy messaging, and status helpers.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["workspace", "account"],
    blocks: ["policy-panel", "settings-groups", "verification-steps"],
    related: ["form-create-edit", "team-roles-starter"],
    surfaces: ["switches", "radio groups", "alert panels", "verification lists"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["settingGroup", "policyRule", "verificationStep"],
      slots: ["sectionNav", "settingsBody", "statusRail"],
      outputs: ["settings map", "policy posture"],
      samples: ["settings.json", "policies.json"],
    },
  },
  {
    slug: "team-roles-starter",
    name: "Team Roles Starter",
    group: "saas",
    shell: "AdminShell",
    summary: "Membership management starter with invites, roles, seats, and audit framing.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["internal team", "customer admin"],
    blocks: ["member-table", "invite-card", "entitlement-summary"],
    related: ["billing-plans-starter", "settings-sectioned"],
    surfaces: ["avatar list", "table", "badge", "sheet"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["member", "role", "invite"],
      slots: ["memberTable", "invitePanel", "seatSummary"],
      outputs: ["member roster", "pending invites"],
      samples: ["members.json", "roles.json"],
    },
  },
  {
    slug: "billing-plans-starter",
    name: "Billing Plans Starter",
    group: "saas",
    shell: "AdminShell",
    summary: "Pricing and usage starter with entitlements framing, usage bars, and trust copy.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["founder", "enterprise"],
    blocks: ["pricing-grid", "usage-summary", "entitlement-summary"],
    related: ["team-roles-starter", "dashboard-home"],
    surfaces: ["cards", "progress bars", "badges", "comparison table"],
    featuredPackIds: ["normal", "glass", "neon"],
    dataContract: {
      entities: ["plan", "limit", "usageMetric"],
      slots: ["planCards", "usageSummary", "upgradeRail"],
      outputs: ["plan comparison", "usage posture"],
      samples: ["plans.json", "usage.json"],
    },
  },
  {
    slug: "onboarding-3-step",
    name: "Onboarding 3 Step",
    group: "saas",
    shell: "SidebarShell",
    summary: "Three-step activation flow that leads into the wizard or export.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["self-serve", "team"],
    blocks: ["wizard-steps", "checklist-panel", "verification-steps"],
    related: ["auth/sign-up", "dashboard-home"],
    surfaces: ["step cards", "alerts", "checklist", "support rail"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["step", "check", "workspace"],
      slots: ["stepRail", "stepBody", "completionRail"],
      outputs: ["step status", "activation checklist"],
      samples: ["steps.json", "checks.json"],
    },
  },
  {
    slug: "auth/sign-in",
    name: "Auth Sign In",
    group: "saas",
    shell: "AuthShell",
    summary: "Sign in screen with trust copy, field groups, and help states.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["email-first"],
    blocks: ["auth/login-01", "trust-copy", "social-placeholder"],
    related: ["auth/sign-up", "auth/forgot"],
    surfaces: ["card", "field", "alert", "badge"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["identityProvider", "supportLink"],
      slots: ["authCard", "aside"],
      outputs: ["credential submission"],
      samples: ["sign-in.json"],
    },
  },
  {
    slug: "auth/sign-up",
    name: "Auth Sign Up",
    group: "saas",
    shell: "AuthShell",
    summary: "Sign up flow with value framing, workspace defaults, and reassurance copy.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["invite", "self-serve"],
    blocks: ["auth/signup-01", "benefit-grid", "trust-copy"],
    related: ["auth/sign-in", "onboarding-3-step"],
    surfaces: ["card", "field", "button group", "benefit list"],
    featuredPackIds: ["normal", "glass", "neon"],
    dataContract: {
      entities: ["workspaceSeed", "inviteContext"],
      slots: ["authCard", "benefits"],
      outputs: ["workspace draft", "account details"],
      samples: ["sign-up.json"],
    },
  },
  {
    slug: "auth/forgot",
    name: "Auth Forgot Password",
    group: "saas",
    shell: "AuthShell",
    summary: "Recovery flow with email feedback and reassurance copy.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["email-only"],
    blocks: ["auth/login-01", "status-message"],
    related: ["auth/sign-in", "auth/reset"],
    surfaces: ["card", "alert", "field"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["recoveryRequest"],
      slots: ["recoveryCard"],
      outputs: ["recovery request"],
      samples: ["forgot-password.json"],
    },
  },
  {
    slug: "auth/reset",
    name: "Auth Reset Password",
    group: "saas",
    shell: "AuthShell",
    summary: "Reset form with inline validation and success state.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["single-step"],
    blocks: ["password-reset", "status-message"],
    related: ["auth/sign-in", "auth/forgot"],
    surfaces: ["field", "progress", "alert"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["resetToken"],
      slots: ["resetCard"],
      outputs: ["password update"],
      samples: ["reset-password.json"],
    },
  },
  {
    slug: "landing-section-based",
    name: "Landing Section Based",
    group: "marketing",
    shell: "MarketingShell",
    summary: "Modular marketing shell for hero-to-CTA launches with registry-backed sections.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["product launch", "enterprise"],
    blocks: ["marketing-hero", "feature-grid", "logo-strip", "cta-banner"],
    related: ["pricing-basic", "faq", "contact"],
    surfaces: ["marketing shell", "hero cards", "feature grids", "cta footer"],
    featuredPackIds: ["normal", "glass", "neon"],
    dataContract: {
      entities: ["feature", "quote", "metric"],
      slots: ["hero", "proof", "sections", "cta"],
      outputs: ["marketing page"],
      samples: ["landing-content.json"],
    },
  },
  {
    slug: "pricing-basic",
    name: "Pricing Basic",
    group: "marketing",
    shell: "MarketingShell",
    summary: "Simple pricing surface with trust copy, FAQ handoff, and upgrade moments.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["self-serve", "hybrid"],
    blocks: ["pricing-grid", "faq-accordion", "upgrade-strip"],
    related: ["landing-section-based", "faq", "contact"],
    surfaces: ["cards", "comparison rows", "badge highlights"],
    featuredPackIds: ["normal", "glass", "neon"],
    dataContract: {
      entities: ["plan", "faqEntry"],
      slots: ["pricingGrid", "faq", "cta"],
      outputs: ["pricing page"],
      samples: ["pricing.json", "faq.json"],
    },
  },
  {
    slug: "faq",
    name: "FAQ",
    group: "marketing",
    shell: "MarketingShell",
    summary: "FAQ accordion with conversion support slots and legal/trust framing.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["product", "security"],
    blocks: ["faq-accordion", "contact-strip"],
    related: ["pricing-basic", "legal-layout"],
    surfaces: ["accordion", "alerts", "contact cards"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["faqEntry", "contactPath"],
      slots: ["faqList", "contactStrip"],
      outputs: ["faq page"],
      samples: ["faq.json"],
    },
  },
  {
    slug: "contact",
    name: "Contact",
    group: "marketing",
    shell: "MarketingShell",
    summary: "Contact page with sales paths, support routing, and trust framing.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["sales", "support"],
    blocks: ["contact-shell", "contact-cards", "office-strip"],
    related: ["faq", "legal-layout"],
    surfaces: ["cards", "field", "alert"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["contactPath", "region"],
      slots: ["contactOptions", "form", "trustNotes"],
      outputs: ["contact page"],
      samples: ["contact.json"],
    },
  },
  {
    slug: "legal-layout",
    name: "Legal Layout",
    group: "marketing",
    shell: "DocsShell",
    summary: "Legal content layout with side navigation, trust accents, and article framing.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["privacy", "terms", "security"],
    blocks: ["legal-shell", "docs-article"],
    related: ["docs-article", "faq"],
    surfaces: ["docs shell", "sidebar", "article layout"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["policySection"],
      slots: ["sidebar", "article", "metaRail"],
      outputs: ["policy article"],
      samples: ["policy-sections.json"],
    },
  },
  {
    slug: "docs-home",
    name: "Docs Home",
    group: "docs",
    shell: "DocsShell",
    summary: "Documentation landing page with category rails, quickstarts, and install guidance.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["product", "developer"],
    blocks: ["docs-home-grid", "quickstart-cards", "registry-setup"],
    related: ["docs-article", "changelog"],
    surfaces: ["docs shell", "cards", "search strip"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["docCategory", "quickstart", "registryItem"],
      slots: ["hero", "categoryGrid", "quickstarts", "registrySummary"],
      outputs: ["docs landing"],
      samples: ["docs-home.json"],
    },
  },
  {
    slug: "docs-article",
    name: "Docs Article",
    group: "docs",
    shell: "DocsShell",
    summary: "Article layout with metadata, code samples, registry notes, and sibling nav.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["api", "concept"],
    blocks: ["docs-article", "table-of-contents", "related-articles"],
    related: ["docs-home", "legal-layout"],
    surfaces: ["article shell", "toc", "code panel"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["article", "tocEntry", "registryGuide"],
      slots: ["articleBody", "toc", "related"],
      outputs: ["documentation article"],
      samples: ["article.mdx"],
    },
  },
  {
    slug: "blog-index",
    name: "Blog Index",
    group: "docs",
    shell: "MarketingShell",
    summary: "Journal index for product updates, launch stories, and registry notes.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["product", "culture"],
    blocks: ["article-grid", "category-pills"],
    related: ["blog-article", "changelog"],
    surfaces: ["cards", "filters", "empty state"],
    featuredPackIds: ["normal", "glass", "neon"],
    dataContract: {
      entities: ["post", "tag"],
      slots: ["hero", "filters", "postGrid"],
      outputs: ["post index"],
      samples: ["posts.json"],
    },
  },
  {
    slug: "blog-article",
    name: "Blog Article",
    group: "docs",
    shell: "DocsShell",
    summary: "Editorial article template with pull quotes, metadata, and related strips.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["announcement", "essay"],
    blocks: ["article-hero", "pull-quote", "related-articles"],
    related: ["blog-index", "changelog"],
    surfaces: ["article shell", "quote panel", "related strip"],
    featuredPackIds: ["normal", "glass", "neon"],
    dataContract: {
      entities: ["post", "quote", "author"],
      slots: ["hero", "body", "related"],
      outputs: ["post article"],
      samples: ["post.mdx"],
    },
  },
  {
    slug: "changelog",
    name: "Changelog",
    group: "docs",
    shell: "DocsShell",
    summary: "Release note stream with upgrade guidance, registry updates, and issue tracking hooks.",
    states: ["loading", "empty", "error", "success", "no access"],
    variants: ["product", "package"],
    blocks: ["release-feed", "upgrade-guide", "registry-summary"],
    related: ["docs-home", "blog-index"],
    surfaces: ["timeline", "badge", "article cards"],
    featuredPackIds: ["normal", "glass"],
    dataContract: {
      entities: ["release", "upgradeNote", "registryItem"],
      slots: ["releaseFeed", "upgradeGuide", "registrySummary"],
      outputs: ["changelog page"],
      samples: ["releases.json"],
    },
  },
] as TemplateManifest[];

export function listTemplates(group?: string) {
  return group
    ? templates.filter((template) => template.group === group)
    : templates;
}

export function getTemplateBySlug(slug: string) {
  return templates.find((template) => template.slug === slug);
}

export function listTemplateStates(slug: string) {
  return getTemplateBySlug(slug)?.states ?? [];
}
