export * from "./foundation";
export * from "./controls";
export * from "./overlays";
export * from "./menus";
export * from "./data";
export * from "./sidebar";
export * from "./lib/utils";
export { toast, Toaster } from "sonner";

export const coreComponentCatalog = [
  "accordion",
  "alert",
  "alert-dialog",
  "avatar",
  "badge",
  "breadcrumb",
  "button",
  "button-group",
  "calendar",
  "card",
  "chart",
  "checkbox",
  "combobox",
  "command",
  "context-menu",
  "dialog",
  "drawer",
  "dropdown-menu",
  "empty",
  "field",
  "form",
  "hover-card",
  "input",
  "input-group",
  "input-otp",
  "kbd",
  "menubar",
  "navigation-menu",
  "pagination",
  "popover",
  "progress",
  "radio-group",
  "resizable",
  "scroll-area",
  "select",
  "separator",
  "sheet",
  "sidebar",
  "skeleton",
  "slider",
  "spinner",
  "switch",
  "table",
  "data-table",
  "tabs",
  "textarea",
  "toggle",
  "toggle-group",
  "tooltip",
  "typography",
] as const;
